name: Validate Samples on Merge


on:
  pull_request:
    branches: [ main ]


jobs:
  validate-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create a .fhir for the chached resources of the FHIR profile
        run: mkdir -p ~/.fhir
      
      - name: Download the cache content of the FHIR Validator
        run: wget https://figshare.com/ndownloader/files/49362157?private_link=93fbd16af86c3f01a68a -O fhirvalidatorcache.zip
      
      - name: Decompress FHIR Validator Cache
        run: unzip fhirvalidatorcache.zip -d ~/.fhir
      
      - name: Download FHIR Validator
        run: wget https://github.com/hapifhir/org.hl7.fhir.core/releases/download/6.0.10/validator_cli.jar
      
      - name: Set FHIR Validator Path
        run: echo "FHIR_VALIDATOR_PATH=$(pwd)/validator_cli.jar" >> $GITHUB_ENV
      
      - name: Checking if the pairing rules generate valid FHIR resources from a set of CDF data samples
        run: npm run validatesamples
        continue-on-error: false
